import spacy
nlp = spacy.load("custom_financial_ner")
ruler = nlp.get_pipe("entity_ruler")

test_texts = [
    "What was Abbott Limited India's % Change in Equity Value 2024?",
    "What was Abbott Limited India's % Change in Mcap 2024?",
    "What was Abbott Limited India's % Change in Net Tangible Asset Value 2024?",
    "What was Abbott Limited India's % Growth in EBIT 2024?",
    "What was Abbott Limited India's % Growth in NPAT 2024?",
    "What was Abbott Limited India's % Growth in NPAT (W/o Exceptional Items) 2024?",
    "What was Abbott Limited India's % Growth in PBT 2024?",
    "What was Abbott Limited India's (Increase)/Decrease in Cash 2024?",
    "What was Abbott Limited India's (Increase)/Decrease in Overall Equity 2024?",
    "What was Abbott Limited India's (Invested)/generated from Net Working Assets 2024?",
    "What was Abbott Limited India's Acid Ratio 2024?",
    "What was Abbott Limited India's Borrowing 2024?",
    "What was Abbott Limited India's Borrowing (% of Total) 2024?",
    "What was Abbott Limited India's Borrowings to EBITDA Ratio 2024?",
    "What was Abbott Limited India's Borrowings to Equity Ratio 2024?",
    "What was Abbott Limited India's Cash and Cash Equivalents 2024?",
    "What is Apple's % Growth in PBT 2024?",
    "Apple's % Change in Net Tangible Asset Value 2024?",
    "What is Tesla's Year-over-Year Revenue Growth for Q4 2024?",
    "What is 10X Genomics's Net Margin % (Based on P&L) in 2024?",
    "What is Apple's Cash Available to Satisfy Finance Providers 2024?",
    "What is Apple's Cash Flow Availability before Financing Yield 2024?",
    "What is Apple's Cash Flow Available to Satisfy Finance Providers Yield 2024?",
    "What is Apple's CFO Salary 2024?",
    "What is Apple's CFO Salary as % of Revenue 2024?",
    "What is Apple's Change of Accounting Principle 2024?",
    "What is Apple's Common stock withheld related to net share settlement of equity awards 2024?",
    "What is Apple's Company Secretary Salary 2024?",
    "What is Apple's Company Secretary Salary as % of Revenue 2024?",
    "What is Apple's Cost of Sales 2024?",
    "What is Apple's Current assets to Current liabilities Ratio 2024?",
    "What is Apple's Current Borrowing 2024?",
    "What is Apple's Current Borrowing (% of Total) 2024?",
    "What is Apple's Days of Inventory 2024?",
    "What is Apple's Days of Payable 2024?",
    "What is Apple's Days of Receivable 2024?",
    "What is Apple's Debt Service Capability (Cash Flow) 2024?",
    "What is Apple's Debt Service Capability (Profit & Loss) 2024?",
    "What is Apple's Debt Service Cost 2024?",
    "What is Apple's Debt Service Cost (P&L) % 2024?",
    "What is Apple's Debt Service Cost Coverage Ratio 2024?",
    "What is Apple's Debt Service Cost Paid 2024?",
    "What is Apple's Debt Service Cost Paid (Cash Flow) % 2024?",
    "What is Apple's Debt Service Costs 2024?",
    "What is Apple's Debt Service Costs (% of Revenue) 2024?",
    "What is Apple's Debt Service Costs Leases 2024?",
    "What is Apple's Depreciation & Amortisation 2024?",
    "What is Apple's Depreciation/Amortisation - Leases As % of Right of Asset Use 2024?",
    "What is Apple's Depreciation and Amortisation 2024?",
    "What is Apple's Depreciation and Amortisation (% of Revenue) 2024?",
    "What is Apple's Depreciation as % of Fixed Assets/Intangibles 2024?",
    "What is Apple's Dividend & Dividend Tax Paid 2024?",
    "What is Apple's Dividend & Taxes (Based on Cash Flow) 2024?",
    "What is Apple's Dividend & Taxes (Based on Equity Statement) 2024?",
    "What is Apple's Dividend Paid 2024?",
    "What is Apple's Dividend Payout Ratio 2024?",
    "What is Apple's Dividend Payout Ratio (Based on NPAT w/o Exceptional Items) 2024?",
    "What is Apple's Dividend Proposed 2024?",
    "What is Apple's Dividend Tax 2024?",
    "What is Apple's Dividend Yield 2024?",
    "What is Apple's Dow Jones Return 2024?",
    "What is Apple's Earning Before Interest and Tax (EBIT) 2024?",
    "what was ebit % for Coca cola in year 2022?",
    "What is 10X Genomics's net margin % (based on p&l) in 2024?",
]

for text in test_texts:
    #print(text[8:46])
    doc = nlp(text)
    print(f"\nText: {text}")
    for ent in doc.ents:
        print(f"Entity: {ent.text}, Label: {ent.label_}")
